CREATE SCHEMA IF NOT EXISTS spiral;

CREATE TABLE IF NOT EXISTS spiral.metadata (
    view_name TEXT PRIMARY KEY,
    parent_view TEXT NOT NULL,
    frame_seconds INTEGER NOT NULL,
    base_view TEXT NOT NULL,
    scope_columns TEXT[] NOT NULL DEFAULT '{}',
    columns_metadata JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS spiral.sources (
    view_name TEXT NOT NULL,
    base_view TEXT NOT NULL,
    frame_seconds INTEGER NOT NULL,
    base_column TEXT NOT NULL,
    formula TEXT NOT NULL,
    mat_column TEXT NOT NULL,
    rollup_gsub_strategy TEXT,
    metadata JSONB NOT NULL DEFAULT '{}',
    PRIMARY KEY (view_name, base_column, formula)
);

CREATE TABLE IF NOT EXISTS spiral.changelog (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_view TEXT NOT NULL,
    scope_values JSONB NOT NULL DEFAULT '{}',
    t_start BIGINT NOT NULL,
    t_end BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_spiral_changelog_base ON spiral.changelog (base_view);
CREATE UNIQUE INDEX IF NOT EXISTS idx_spiral_changelog_event_id ON spiral.changelog (event_id);

CREATE TYPE time_value_spiral AS (v double precision, t bigint);

CREATE OR REPLACE FUNCTION first_spiral_sfunc(state time_value_spiral, val double precision, ts bigint) RETURNS time_value_spiral AS $$
    BEGIN RETURN CASE WHEN state IS NULL OR ts < state.t THEN (val, ts)::time_value_spiral ELSE state END; END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION last_spiral_sfunc(state time_value_spiral, val double precision, ts bigint) RETURNS time_value_spiral AS $$
    BEGIN RETURN CASE WHEN state IS NULL OR ts >= state.t THEN (val, ts)::time_value_spiral ELSE state END; END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION first_spiral_final(state time_value_spiral) RETURNS double precision AS $$
    BEGIN RETURN CASE WHEN state IS NULL THEN NULL ELSE state.v END; END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE AGGREGATE first(double precision, bigint) (
    sfunc = first_spiral_sfunc,
    stype = time_value_spiral,
    finalfunc = first_spiral_final
);

CREATE AGGREGATE last(double precision, bigint) (
    sfunc = last_spiral_sfunc,
    stype = time_value_spiral,
    finalfunc = first_spiral_final
);

-- PASSTHROUGHS & HELPERS
CREATE OR REPLACE FUNCTION to_timestamptz(BIGINT) RETURNS TIMESTAMPTZ AS $$
    SELECT spiral_from_epoch($1);
$$ LANGUAGE SQL IMMUTABLE PARALLEL SAFE;

-- track_changes_stmt(base_view, bucket_seconds)
-- Records one changelog entry per frame-aligned time bucket touched by the
-- statement, rather than a single MIN..MAX span over the whole batch.
-- This bounds refresh cost to O(buckets touched) instead of O(time span),
-- eliminating dirty-range amplification from sparse bulk operations.
CREATE OR REPLACE FUNCTION spiral.track_changes_stmt() RETURNS TRIGGER AS $$
DECLARE
    v_base_view    TEXT   := TG_ARGV[0];
    -- Fall back to 3600s (1h) for triggers created before bucket_secs arg was added.
    v_bucket_secs  BIGINT := COALESCE(NULLIF(TG_ARGV[1], '')::BIGINT, 3600);
    v_scope_columns TEXT[];
    v_has_scopes BOOLEAN;
    v_sql TEXT;
BEGIN
    SELECT scope_columns INTO v_scope_columns
    FROM spiral.metadata
    WHERE view_name = v_base_view;

    v_has_scopes := array_length(v_scope_columns, 1) > 0;

    IF v_has_scopes THEN
        DECLARE
            v_json_build TEXT;
            v_cols_csv TEXT;
            v_union_sql TEXT := '';
        BEGIN
            SELECT string_agg(quote_literal(col) || ', "' || col || '"', ', '),
                   string_agg('"' || col || '"', ', ')
            INTO v_json_build, v_cols_csv
            FROM unnest(v_scope_columns) as col;

            v_json_build := 'jsonb_build_object(' || v_json_build || ')';

            IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
                v_union_sql := 'SELECT t, ' || v_cols_csv || ' FROM new_table';
            END IF;
            IF (TG_OP = 'DELETE' OR TG_OP = 'UPDATE') THEN
                IF v_union_sql <> '' THEN
                    v_union_sql := v_union_sql || ' UNION ALL ';
                END IF;
                v_union_sql := v_union_sql || 'SELECT t, ' || v_cols_csv || ' FROM old_table';
            END IF;

            -- One row per (scope, frame-bucket) instead of one MIN..MAX per scope.
            v_sql := 'INSERT INTO spiral.changelog (base_view, scope_values, t_start, t_end) ' ||
                     'SELECT $1, ' || v_json_build || ', bucket, bucket + ' || v_bucket_secs || ' ' ||
                     'FROM (SELECT ' || v_cols_csv || ', ' ||
                     '      (spiral(t::timestamptz) / ' || v_bucket_secs || ') * ' || v_bucket_secs || ' AS bucket ' ||
                     '      FROM (' || v_union_sql || ') sub ' ||
                     '      GROUP BY ' || v_cols_csv || ', bucket) bucketed';

            EXECUTE v_sql USING v_base_view;
        END;
    ELSE
        DECLARE
            v_union_sql TEXT := '';
        BEGIN
            IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
                v_union_sql := 'SELECT t FROM new_table';
            END IF;
            IF (TG_OP = 'DELETE' OR TG_OP = 'UPDATE') THEN
                IF v_union_sql <> '' THEN
                    v_union_sql := v_union_sql || ' UNION ALL ';
                END IF;
                v_union_sql := v_union_sql || 'SELECT t FROM old_table';
            END IF;

            -- One row per frame-bucket instead of one MIN..MAX per statement.
            v_sql := 'INSERT INTO spiral.changelog (base_view, scope_values, t_start, t_end) ' ||
                     'SELECT $1, ''{}''::jsonb, bucket, bucket + ' || v_bucket_secs || ' ' ||
                     'FROM (SELECT (spiral(t::timestamptz) / ' || v_bucket_secs || ') * ' || v_bucket_secs || ' AS bucket ' ||
                     '      FROM (' || v_union_sql || ') sub ' ||
                     '      GROUP BY bucket) bucketed';

            EXECUTE v_sql USING v_base_view;
        END;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql
SET search_path = public, spiral, "$user";

-- STORAGE ALIASES
CREATE OR REPLACE FUNCTION spiral_pack_delta_zero(text, int) RETURNS void AS 'SELECT spiral_pack_delta($1, $2)' LANGUAGE SQL;
CREATE OR REPLACE FUNCTION spiral_read_main_zero(int, bigint, bigint) RETURNS double precision AS 'SELECT spiral_read_main($1, $2, $3)' LANGUAGE SQL;

-- LEGACY SUPPORT
CREATE OR REPLACE FUNCTION first_pg_sfunc(state time_value_spiral, val double precision, ts bigint) RETURNS time_value_spiral AS 'SELECT first_spiral_sfunc($1, $2, $3)' LANGUAGE SQL;
CREATE OR REPLACE FUNCTION last_pg_sfunc(state time_value_spiral, val double precision, ts bigint) RETURNS time_value_spiral AS 'SELECT last_spiral_sfunc($1, $2, $3)' LANGUAGE SQL;

-- ROBUST REGISTER WRAPPER
CREATE OR REPLACE FUNCTION spiral_register_view(
    view_name text, 
    parent_view text, 
    frame_seconds integer, 
    base_view text, 
    scope_columns text[]
) RETURNS void AS $$
BEGIN
    -- This calls the Rust function
    PERFORM spiral_register_view_rust(view_name, parent_view, frame_seconds, base_view, scope_columns);
END;
$$ LANGUAGE plpgsql
SET search_path = public, spiral, "$user";

-- Missing functions from demo.sql
CREATE OR REPLACE FUNCTION to_spiraling_number(t BIGINT, cycle INTEGER, lane INTEGER) RETURNS BIGINT AS $$
    SELECT spiral_zorder($1, ARRAY[$2::text, $3::text]);
$$ LANGUAGE SQL IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION to_spiral(t BIGINT, cycle INTEGER) RETURNS BOX AS $$
    SELECT box(point(($1 % $2)::double precision, ($1 / $2)::double precision), 
               point(($1 % $2 + 10)::double precision, ($1 / $2 + 10)::double precision));
$$ LANGUAGE SQL IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION spiral_create_partition(table_name TEXT, range_size BIGINT, partition_id INTEGER) RETURNS VOID AS $$
DECLARE
    v_start BIGINT := range_size * partition_id;
    v_end BIGINT := range_size * (partition_id + 1);
    v_part_name TEXT := table_name || '_' || partition_id;
BEGIN
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)', 
                   v_part_name, table_name, v_start, v_end);
END;
$$ LANGUAGE plpgsql;

-- DOCS SUPPORT
CREATE OR REPLACE VIEW spiral.available_sources AS
SELECT
    m.base_view,
    m.view_name,
    m.frame_seconds,
    s.base_column,
    s.formula,
    s.mat_column,
    s.rollup_gsub_strategy
FROM spiral.metadata m
JOIN spiral.sources s ON m.view_name = s.view_name
ORDER BY m.base_view, m.frame_seconds;

-- OBSERVABILITY
-- spiral.status: one row per base table — hierarchy health, dirty backlog,
-- and an approximate rollup lag (time since newest unprocessed data bucket).
-- lag is NULL when no unprocessed entries exist (rollup is fully current).
CREATE OR REPLACE VIEW spiral.status AS
WITH roots AS (
    SELECT DISTINCT base_view
    FROM spiral.metadata
    WHERE parent_view = 'BASE'
),
tiers AS (
    SELECT base_view, COUNT(*) AS tier_count
    FROM spiral.metadata
    WHERE frame_seconds > 0
    GROUP BY base_view
),
dirty AS (
    SELECT
        base_view,
        COUNT(*)                                      AS dirty_entries,
        COUNT(DISTINCT scope_values)                  AS dirty_scopes,
        SUM(t_end - t_start)                          AS dirty_seconds,
        to_timestamptz(MIN(t_start)::bigint)           AS oldest_dirty_ts,
        to_timestamptz(MAX(t_end)::bigint)             AS newest_dirty_ts
    FROM spiral.changelog
    GROUP BY base_view
)
SELECT
    r.base_view,
    COALESCE(t.tier_count, 0)::int              AS tier_count,
    COALESCE(d.dirty_entries, 0)::bigint        AS dirty_entries,
    COALESCE(d.dirty_scopes,  0)::bigint        AS dirty_scopes,
    COALESCE(d.dirty_seconds, 0)::bigint        AS dirty_seconds,
    d.oldest_dirty_ts                           AS oldest_dirty_ts,
    d.newest_dirty_ts                           AS newest_dirty_ts,
    CASE WHEN d.newest_dirty_ts IS NOT NULL
         THEN now() - d.newest_dirty_ts
         ELSE NULL::interval
    END                                         AS lag
FROM roots r
LEFT JOIN tiers t ON t.base_view = r.base_view
LEFT JOIN dirty  d ON d.base_view = r.base_view;

-- spiral_lag(base_view): returns the rollup lag for a single base table as
-- an INTERVAL, or NULL if the rollup is fully current.
-- Lag = time elapsed since the newest unprocessed data bucket's end timestamp.
CREATE OR REPLACE FUNCTION spiral_lag(base_view text) RETURNS INTERVAL AS $$
    SELECT now() - to_timestamptz(MAX(t_end)::bigint)
    FROM spiral.changelog
    WHERE changelog.base_view = $1
$$ LANGUAGE SQL STABLE PARALLEL SAFE;

-- spiral.scope_status: per-(base_view, scope) lag and backlog.
-- Useful for identifying hot or lagging tenants under concurrent write load.
-- lag is NULL when the scope has no unprocessed entries.
CREATE OR REPLACE VIEW spiral.scope_status AS
SELECT
    base_view,
    scope_values,
    COUNT(*)                                        AS dirty_entries,
    SUM(t_end - t_start)                            AS dirty_seconds,
    to_timestamptz(MIN(t_start)::bigint)            AS oldest_dirty_ts,
    to_timestamptz(MAX(t_end)::bigint)              AS newest_dirty_ts,
    now() - to_timestamptz(MAX(t_end)::bigint)      AS lag
FROM spiral.changelog
GROUP BY base_view, scope_values
ORDER BY lag DESC NULLS LAST;
